# a = input ('ввидите число')
# num  = int(a)
# # print(num)
# # print(type(num))
# # print('данные переменных:', a, num)
# print ('В переиенной а храница:', a, 'её тип данных', type(a))
# print('В переменной а храница:', a, 'её тип данных', type(num))
